// Code generated by mockery v1.0.0. DO NOT EDIT.

package inventory

import mock "github.com/stretchr/testify/mock"

// mockDsnPreparer is an autogenerated mock type for the dsnPreparer type
type mockDsnPreparer struct {
	mock.Mock
}

// MongoDBDSN provides a mock function with given fields: host, port, username, password
func (_m *mockDsnPreparer) MongoDBDSN(host string, port uint16, username string, password string) string {
	ret := _m.Called(host, port, username, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, uint16, string, string) string); ok {
		r0 = rf(host, port, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MySQLDSN provides a mock function with given fields: host, port, username, password
func (_m *mockDsnPreparer) MySQLDSN(host string, port uint16, username string, password string) string {
	ret := _m.Called(host, port, username, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, uint16, string, string) string); ok {
		r0 = rf(host, port, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PostgreSQLDSN provides a mock function with given fields: host, port, username, password
func (_m *mockDsnPreparer) PostgreSQLDSN(host string, port uint16, username string, password string) string {
	ret := _m.Called(host, port, username, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, uint16, string, string) string); ok {
		r0 = rf(host, port, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
