// Code generated by mockery v1.0.0. DO NOT EDIT.

package inventory

import context "context"
import mock "github.com/stretchr/testify/mock"

// mockRegistry is an autogenerated mock type for the registry type
type mockRegistry struct {
	mock.Mock
}

// Kick provides a mock function with given fields: ctx, agentID
func (_m *mockRegistry) Kick(ctx context.Context, agentID string) {
	_m.Called(ctx, agentID)
}

// SendSetStateRequest provides a mock function with given fields: ctx, agentID
func (_m *mockRegistry) SendSetStateRequest(ctx context.Context, agentID string) {
	_m.Called(ctx, agentID)
}
