// Code generated by mockery v1.0.0. DO NOT EDIT.

package agents

import any "github.com/golang/protobuf/ptypes/any"
import context "context"
import mock "github.com/stretchr/testify/mock"

// mockQanClient is an autogenerated mock type for the qanClient type
type mockQanClient struct {
	mock.Mock
}

// TODO provides a mock function with given fields: ctx, m
func (_m *mockQanClient) TODO(ctx context.Context, m *any.Any) {
	_m.Called(ctx, m)
}
