// Code generated by mockery v1.0.0. DO NOT EDIT.

package management

import (
	mock "github.com/stretchr/testify/mock"

	models "github.com/percona/pmm-managed/models"
)

// mockDefaultsFileParser is an autogenerated mock type for the defaultsFileParser type
type mockDefaultsFileParser struct {
	mock.Mock
}

// ParseDefaultsFile provides a mock function with given fields: pmmAgentID, filePath, serviceType
func (_m *mockDefaultsFileParser) ParseDefaultsFile(pmmAgentID string, filePath string, serviceType models.ServiceType) (string, string, error) {
	ret := _m.Called(pmmAgentID, filePath, serviceType)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, models.ServiceType) string); ok {
		r0 = rf(pmmAgentID, filePath, serviceType)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string, string, models.ServiceType) string); ok {
		r1 = rf(pmmAgentID, filePath, serviceType)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, models.ServiceType) error); ok {
		r2 = rf(pmmAgentID, filePath, serviceType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
