// Code generated by go-swagger; DO NOT EDIT.

package r_d_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/percona/pmm-managed/api/swagger/models"
)

// DiscoverMixin5Reader is a Reader for the DiscoverMixin5 structure.
type DiscoverMixin5Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DiscoverMixin5Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDiscoverMixin5OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDiscoverMixin5OK creates a DiscoverMixin5OK with default headers values
func NewDiscoverMixin5OK() *DiscoverMixin5OK {
	return &DiscoverMixin5OK{}
}

/*DiscoverMixin5OK handles this case with default header values.

(empty)
*/
type DiscoverMixin5OK struct {
	Payload *models.APIRDSDiscoverResponse
}

func (o *DiscoverMixin5OK) Error() string {
	return fmt.Sprintf("[POST /v0/rds/discover][%d] discoverMixin5OK  %+v", 200, o.Payload)
}

func (o *DiscoverMixin5OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRDSDiscoverResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
