// Code generated by go-swagger; DO NOT EDIT.

package r_d_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/percona/pmm-managed/api/swagger/models"
)

// NewDiscoverMixin5Params creates a new DiscoverMixin5Params object
// with the default values initialized.
func NewDiscoverMixin5Params() *DiscoverMixin5Params {
	var ()
	return &DiscoverMixin5Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDiscoverMixin5ParamsWithTimeout creates a new DiscoverMixin5Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDiscoverMixin5ParamsWithTimeout(timeout time.Duration) *DiscoverMixin5Params {
	var ()
	return &DiscoverMixin5Params{

		timeout: timeout,
	}
}

// NewDiscoverMixin5ParamsWithContext creates a new DiscoverMixin5Params object
// with the default values initialized, and the ability to set a context for a request
func NewDiscoverMixin5ParamsWithContext(ctx context.Context) *DiscoverMixin5Params {
	var ()
	return &DiscoverMixin5Params{

		Context: ctx,
	}
}

// NewDiscoverMixin5ParamsWithHTTPClient creates a new DiscoverMixin5Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDiscoverMixin5ParamsWithHTTPClient(client *http.Client) *DiscoverMixin5Params {
	var ()
	return &DiscoverMixin5Params{
		HTTPClient: client,
	}
}

/*DiscoverMixin5Params contains all the parameters to send to the API endpoint
for the discover mixin5 operation typically these are written to a http.Request
*/
type DiscoverMixin5Params struct {

	/*Body*/
	Body *models.APIRDSDiscoverRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the discover mixin5 params
func (o *DiscoverMixin5Params) WithTimeout(timeout time.Duration) *DiscoverMixin5Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the discover mixin5 params
func (o *DiscoverMixin5Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the discover mixin5 params
func (o *DiscoverMixin5Params) WithContext(ctx context.Context) *DiscoverMixin5Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the discover mixin5 params
func (o *DiscoverMixin5Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the discover mixin5 params
func (o *DiscoverMixin5Params) WithHTTPClient(client *http.Client) *DiscoverMixin5Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the discover mixin5 params
func (o *DiscoverMixin5Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the discover mixin5 params
func (o *DiscoverMixin5Params) WithBody(body *models.APIRDSDiscoverRequest) *DiscoverMixin5Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the discover mixin5 params
func (o *DiscoverMixin5Params) SetBody(body *models.APIRDSDiscoverRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DiscoverMixin5Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
