// Code generated by go-swagger; DO NOT EDIT.

package r_d_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new r d s API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for r d s API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AddMixin5 add mixin5 API
*/
func (a *Client) AddMixin5(params *AddMixin5Params) (*AddMixin5OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddMixin5Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "AddMixin5",
		Method:             "POST",
		PathPattern:        "/v0/rds",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AddMixin5Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AddMixin5OK), nil

}

/*
Discover discover API
*/
func (a *Client) Discover(params *DiscoverParams) (*DiscoverOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDiscoverParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Discover",
		Method:             "POST",
		PathPattern:        "/v0/rds/discover",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DiscoverReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DiscoverOK), nil

}

/*
ListMixin5 list mixin5 API
*/
func (a *Client) ListMixin5(params *ListMixin5Params) (*ListMixin5OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListMixin5Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ListMixin5",
		Method:             "GET",
		PathPattern:        "/v0/rds",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListMixin5Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListMixin5OK), nil

}

/*
RemoveMixin5 remove mixin5 API
*/
func (a *Client) RemoveMixin5(params *RemoveMixin5Params) (*RemoveMixin5OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRemoveMixin5Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "RemoveMixin5",
		Method:             "DELETE",
		PathPattern:        "/v0/rds",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RemoveMixin5Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RemoveMixin5OK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
