// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// APIPostgreSQLRemoveRequest api postgre SQL remove request
// swagger:model apiPostgreSQLRemoveRequest
type APIPostgreSQLRemoveRequest struct {

	// address
	Address string `json:"address,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`
}

// Validate validates this api postgre SQL remove request
func (m *APIPostgreSQLRemoveRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIPostgreSQLRemoveRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPostgreSQLRemoveRequest) UnmarshalBinary(b []byte) error {
	var res APIPostgreSQLRemoveRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
