// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// APIPostgreSQLInstanceID api postgre SQL instance ID
// swagger:model apiPostgreSQLInstanceID
type APIPostgreSQLInstanceID struct {

	// name
	Name string `json:"name,omitempty"`

	// region
	Region string `json:"region,omitempty"`
}

// Validate validates this api postgre SQL instance ID
func (m *APIPostgreSQLInstanceID) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIPostgreSQLInstanceID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPostgreSQLInstanceID) UnmarshalBinary(b []byte) error {
	var res APIPostgreSQLInstanceID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
