// Code generated by mockery v1.0.0. DO NOT EDIT.

package dbaas

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockDbaasClient is an autogenerated mock type for the dbaasClient type
type mockDbaasClient struct {
	mock.Mock
}

// CheckKubernetesClusterConnection provides a mock function with given fields: ctx, kubeConfig
func (_m *mockDbaasClient) CheckKubernetesClusterConnection(ctx context.Context, kubeConfig string) error {
	ret := _m.Called(ctx, kubeConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, kubeConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
