// Code generated by mockery v1.0.0. DO NOT EDIT.

package checks

import (
	alert "github.com/percona/pmm/api/alertmanager/amclient/alert"
	ammodels "github.com/percona/pmm/api/alertmanager/ammodels"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockAlertmanagerService is an autogenerated mock type for the alertmanagerService type
type mockAlertmanagerService struct {
	mock.Mock
}

// GetAlerts provides a mock function with given fields: params
func (_m *mockAlertmanagerService) GetAlerts(params alert.GetAlertsParams) ([]*ammodels.GettableAlert, error) {
	ret := _m.Called(params)

	var r0 []*ammodels.GettableAlert
	if rf, ok := ret.Get(0).(func(alert.GetAlertsParams) []*ammodels.GettableAlert); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ammodels.GettableAlert)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(alert.GetAlertsParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendAlerts provides a mock function with given fields: ctx, alerts
func (_m *mockAlertmanagerService) SendAlerts(ctx context.Context, alerts ammodels.PostableAlerts) {
	_m.Called(ctx, alerts)
}
