// Code generated by mockery v1.0.0. DO NOT EDIT.

package checks

import (
	mock "github.com/stretchr/testify/mock"

	services "github.com/percona/pmm-managed/services"

	time "time"
)

// mockAlertRegistry is an autogenerated mock type for the alertRegistry type
type mockAlertRegistry struct {
	mock.Mock
}

// CreateAlert provides a mock function with given fields: alertParams, delayFor
func (_m *mockAlertRegistry) CreateAlert(alertParams *services.AlertParams, delayFor time.Duration) {
	_m.Called(alertParams, delayFor)
}

// RemovePrefix provides a mock function with given fields: prefix, keepIDs
func (_m *mockAlertRegistry) RemovePrefix(prefix string, keepIDs map[string]struct{}) {
	_m.Called(prefix, keepIDs)
}
