// Code generated by mockery v1.0.0. DO NOT EDIT.

package server

import mock "github.com/stretchr/testify/mock"

// mockRulesService is an autogenerated mock type for the rulesService type
type mockRulesService struct {
	mock.Mock
}

// RemoveVMAlertRulesFiles provides a mock function with given fields:
func (_m *mockRulesService) RemoveVMAlertRulesFiles() {
	_m.Called()
}

// WriteVMAlertRulesFiles provides a mock function with given fields:
func (_m *mockRulesService) WriteVMAlertRulesFiles() {
	_m.Called()
}
