// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// rulesService is an autogenerated mock type for the rulesService type
type mockRulesService struct {
	mock.Mock
}

// RemoveVMAlertRulesFiles provides a mock function with given fields:
func (_m *rulesService) RemoveVMAlertRulesFiles() {
	_m.Called()
}

// WriteVMAlertRulesFiles provides a mock function with given fields:
func (_m *rulesService) WriteVMAlertRulesFiles() {
	_m.Called()
}
