// Code generated by mockery v1.0.0. DO NOT EDIT.

package server

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockChecksService is an autogenerated mock type for the checksService type
type mockChecksService struct {
	mock.Mock
}

// CleanupAlerts provides a mock function with given fields:
func (_m *mockChecksService) CleanupAlerts() {
	_m.Called()
}

// StartChecks provides a mock function with given fields: ctx, checkNames
func (_m *mockChecksService) StartChecks(ctx context.Context, checkNames []string) error {
	ret := _m.Called(ctx, checkNames)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, checkNames)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
