services:
  platform:
    skip_tls_verification: false
  telemetry:
    enabled: false
    # priority is as follows, from the highest priority
    #   1. this config value
    #   2. PERCONA_TEST_SAAS_HOST env variable
    #   3. check.percona.com
    #saas_hostname:
    reporting:
      # priority is as follows, from the highest priority
      #   1. value from env name provided by `interval_env`
      #   2. this config value
      interval: 24h
      interval_env: "PERCONA_TEST_TELEMETRY_INTERVAL"
      # priority is as follows, from the highest priority
      #   1. value from env name provided by `retry_backoff_env`
      #   2. this config value
      retry_backoff: 1h
      retry_backoff_env: "PERCONA_TEST_TELEMETRY_RETRY_BACKOFF"
      retry_count: 20
      send_timeout: 5s
    v1_url_env: "PERCONA_VERSION_CHECK_URL"
    # priority is as follows, from the highest priority
    #   1. value from env name provided by `v1_url_env`
    #   2. this config value
    v1_url: https://v.percona.com/
    endpoints:
      # %s is substituted with `saas_hostname`
      report: https://%s/v1/telemetry/Report
  telemetry_v2:
    enabled: true
    config_location: /etc/percona/telemetry/*.yml
    disable_signing_verification: false
    signing:
      trusted_public_keys:
        - RWToO+zBnSKDsXC2k64DZ23kwgRW52+BtHfYtFM1NC8MoNL7LxxgoyKn # TODO: must be removed after config is signed with legit key
    datasources:
      VM:
        enabled: true
        timeout: 2s
        address: http://localhost:9090/prometheus
      QANDB_SELECT:
        enabled: true
        timeout: 2s
        dsn: tcp://localhost:9000?database=pmm&block_size=10000&pool_size=2
      PMMDB_SELECT:
        enabled: true
        timeout: 10s
        use_separate_credentials: false
        separate_credentials:
          username: pmm
          password: pmm
    reporting:
      skip_tls_verification: false
      send_on_start: false
      interval: 24h
      interval_env: "PERCONA_TEST_TELEMETRY_INTERVAL"
      retry_backoff: 1h
      retry_backoff_env: "PERCONA_TEST_TELEMETRY_RETRY_BACKOFF"
      retry_count: 20
      send_timeout: 5s
extra_headers:
  enabled: false
#  endpoints:
#    - method: POST
#      endpoint: http://localhost:20202/v1/telemetry/Report
#      headers:
#        Auth-Status: "0"
#        Grpc-Metadata-X-Real-IP: "188.255.42.42"
