services:
  platform:
    skip_tls_verification: false
  telemetry:
    enabled: true
    load_defaults: true
    config_location: /etc/percona/telemetry/*.yml
    disable_signing_verification: false
    signing:
      trusted_public_keys:
        - RWToO+zBnSKDsXC2k64DZ23kwgRW52+BtHfYtFM1NC8MoNL7LxxgoyKn # TODO: must be removed after config is signed with legit key
    datasources:
      VM:
        enabled: true
        timeout: 2s
        address: http://localhost:9090/prometheus
      QANDB_SELECT:
        enabled: true
        timeout: 2s
        dsn: tcp://localhost:9000?database=pmm&block_size=10000&pool_size=2
      PMMDB_SELECT:
        enabled: true
        timeout: 10s
        use_separate_credentials: false
        separate_credentials:
          username: pmm
          password: pmm
    reporting:
      skip_tls_verification: false
      send_on_start: false
      interval: 24h
      interval_env: "PERCONA_TEST_TELEMETRY_INTERVAL"
      retry_backoff: 1h
      retry_backoff_env: "PERCONA_TEST_TELEMETRY_RETRY_BACKOFF"
      retry_count: 20
      send_timeout: 5s
extra_headers:
  enabled: false
#  endpoints:
#    - method: POST
#      endpoint: http://localhost:20202/v1/telemetry/Report
#      headers:
#        Auth-Status: "0"
#        Grpc-Metadata-X-Real-IP: "188.255.42.42"
