// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type agentRowTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *agentRowTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("agents").
func (v *agentRowTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *agentRowTableType) Columns() []string {
	return []string{"agent_id", "agent_type", "runs_on_node_id", "created_at", "version", "status", "listen_port", "username", "password", "metrics_url"}
}

// NewStruct makes a new struct for that view or table.
func (v *agentRowTableType) NewStruct() reform.Struct {
	return new(AgentRow)
}

// NewRecord makes a new record for that table.
func (v *agentRowTableType) NewRecord() reform.Record {
	return new(AgentRow)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *agentRowTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// AgentRowTable represents agents view or table in SQL database.
var AgentRowTable = &agentRowTableType{
	s: parse.StructInfo{Type: "AgentRow", SQLSchema: "", SQLName: "agents", Fields: []parse.FieldInfo{{Name: "AgentID", Type: "string", Column: "agent_id"}, {Name: "AgentType", Type: "AgentType", Column: "agent_type"}, {Name: "RunsOnNodeID", Type: "string", Column: "runs_on_node_id"}, {Name: "CreatedAt", Type: "time.Time", Column: "created_at"}, {Name: "Version", Type: "*string", Column: "version"}, {Name: "Status", Type: "*string", Column: "status"}, {Name: "ListenPort", Type: "*uint16", Column: "listen_port"}, {Name: "Username", Type: "*string", Column: "username"}, {Name: "Password", Type: "*string", Column: "password"}, {Name: "MetricsURL", Type: "*string", Column: "metrics_url"}}, PKFieldIndex: 0},
	z: new(AgentRow).Values(),
}

// String returns a string representation of this struct or record.
func (s AgentRow) String() string {
	res := make([]string, 10)
	res[0] = "AgentID: " + reform.Inspect(s.AgentID, true)
	res[1] = "AgentType: " + reform.Inspect(s.AgentType, true)
	res[2] = "RunsOnNodeID: " + reform.Inspect(s.RunsOnNodeID, true)
	res[3] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[4] = "Version: " + reform.Inspect(s.Version, true)
	res[5] = "Status: " + reform.Inspect(s.Status, true)
	res[6] = "ListenPort: " + reform.Inspect(s.ListenPort, true)
	res[7] = "Username: " + reform.Inspect(s.Username, true)
	res[8] = "Password: " + reform.Inspect(s.Password, true)
	res[9] = "MetricsURL: " + reform.Inspect(s.MetricsURL, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *AgentRow) Values() []interface{} {
	return []interface{}{
		s.AgentID,
		s.AgentType,
		s.RunsOnNodeID,
		s.CreatedAt,
		s.Version,
		s.Status,
		s.ListenPort,
		s.Username,
		s.Password,
		s.MetricsURL,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *AgentRow) Pointers() []interface{} {
	return []interface{}{
		&s.AgentID,
		&s.AgentType,
		&s.RunsOnNodeID,
		&s.CreatedAt,
		&s.Version,
		&s.Status,
		&s.ListenPort,
		&s.Username,
		&s.Password,
		&s.MetricsURL,
	}
}

// View returns View object for that struct.
func (s *AgentRow) View() reform.View {
	return AgentRowTable
}

// Table returns Table object for that record.
func (s *AgentRow) Table() reform.Table {
	return AgentRowTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *AgentRow) PKValue() interface{} {
	return s.AgentID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *AgentRow) PKPointer() interface{} {
	return &s.AgentID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *AgentRow) HasPK() bool {
	return s.AgentID != AgentRowTable.z[AgentRowTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *AgentRow) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.AgentID = string(i64)
	} else {
		s.AgentID = pk.(string)
	}
}

// check interfaces
var (
	_ reform.View   = AgentRowTable
	_ reform.Struct = (*AgentRow)(nil)
	_ reform.Table  = AgentRowTable
	_ reform.Record = (*AgentRow)(nil)
	_ fmt.Stringer  = (*AgentRow)(nil)
)

func init() {
	parse.AssertUpToDate(&AgentRowTable.s, new(AgentRow))
}
