// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type backupTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *backupTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("backup_locations").
func (v *backupTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *backupTableType) Columns() []string {
	return []string{
		"id",
		"name",
		"location_name",
		"created_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *backupTableType) NewStruct() reform.Struct {
	return new(Backup)
}

// NewRecord makes a new record for that table.
func (v *backupTableType) NewRecord() reform.Record {
	return new(Backup)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *backupTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// BackupTable represents backup_locations view or table in SQL database.
var BackupTable = &backupTableType{
	s: parse.StructInfo{
		Type:    "Backup",
		SQLName: "backup_locations",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "string", Column: "id"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "LocationName", Type: "string", Column: "location_name"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Backup).Values(),
}

// String returns a string representation of this struct or record.
func (s Backup) String() string {
	res := make([]string, 4)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "LocationName: " + reform.Inspect(s.LocationName, true)
	res[3] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Backup) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.LocationName,
		s.CreatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Backup) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.LocationName,
		&s.CreatedAt,
	}
}

// View returns View object for that struct.
func (s *Backup) View() reform.View {
	return BackupTable
}

// Table returns Table object for that record.
func (s *Backup) Table() reform.Table {
	return BackupTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Backup) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Backup) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Backup) HasPK() bool {
	return s.ID != BackupTable.z[BackupTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Backup) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = BackupTable
	_ reform.Struct = (*Backup)(nil)
	_ reform.Table  = BackupTable
	_ reform.Record = (*Backup)(nil)
	_ fmt.Stringer  = (*Backup)(nil)
)

func init() {
	parse.AssertUpToDate(&BackupTable.s, new(Backup))
}
