// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type checksStateTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *checksStateTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("checks_state").
func (v *checksStateTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *checksStateTableType) Columns() []string {
	return []string{
		"name",
		"interval",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *checksStateTableType) NewStruct() reform.Struct {
	return new(ChecksState)
}

// NewRecord makes a new record for that table.
func (v *checksStateTableType) NewRecord() reform.Record {
	return new(ChecksState)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *checksStateTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ChecksStateTable represents checks_state view or table in SQL database.
var ChecksStateTable = &checksStateTableType{
	s: parse.StructInfo{
		Type:    "ChecksState",
		SQLName: "checks_state",
		Fields: []parse.FieldInfo{
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "Interval", Type: "Interval", Column: "interval"},
		},
		PKFieldIndex: 0,
	},
	z: new(ChecksState).Values(),
}

// String returns a string representation of this struct or record.
func (s ChecksState) String() string {
	res := make([]string, 2)
	res[0] = "Name: " + reform.Inspect(s.Name, true)
	res[1] = "Interval: " + reform.Inspect(s.Interval, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *ChecksState) Values() []interface{} {
	return []interface{}{
		s.Name,
		s.Interval,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *ChecksState) Pointers() []interface{} {
	return []interface{}{
		&s.Name,
		&s.Interval,
	}
}

// View returns View object for that struct.
func (s *ChecksState) View() reform.View {
	return ChecksStateTable
}

// Table returns Table object for that record.
func (s *ChecksState) Table() reform.Table {
	return ChecksStateTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *ChecksState) PKValue() interface{} {
	return s.Name
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *ChecksState) PKPointer() interface{} {
	return &s.Name
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *ChecksState) HasPK() bool {
	return s.Name != ChecksStateTable.z[ChecksStateTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Name = pk.
func (s *ChecksState) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = ChecksStateTable
	_ reform.Struct = (*ChecksState)(nil)
	_ reform.Table  = ChecksStateTable
	_ reform.Record = (*ChecksState)(nil)
	_ fmt.Stringer  = (*ChecksState)(nil)
)

func init() {
	parse.AssertUpToDate(&ChecksStateTable.s, new(ChecksState))
}
