// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type keyValueTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *keyValueTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("key_values").
func (v *keyValueTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *keyValueTableType) Columns() []string {
	return []string{"key", "value"}
}

// NewStruct makes a new struct for that view or table.
func (v *keyValueTableType) NewStruct() reform.Struct {
	return new(KeyValue)
}

// NewRecord makes a new record for that table.
func (v *keyValueTableType) NewRecord() reform.Record {
	return new(KeyValue)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *keyValueTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// KeyValueTable represents key_values view or table in SQL database.
var KeyValueTable = &keyValueTableType{
	s: parse.StructInfo{Type: "KeyValue", SQLSchema: "", SQLName: "key_values", Fields: []parse.FieldInfo{{Name: "Key", Type: "string", Column: "key"}, {Name: "Value", Type: "string", Column: "value"}}, PKFieldIndex: 0},
	z: new(KeyValue).Values(),
}

// String returns a string representation of this struct or record.
func (s KeyValue) String() string {
	res := make([]string, 2)
	res[0] = "Key: " + reform.Inspect(s.Key, true)
	res[1] = "Value: " + reform.Inspect(s.Value, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *KeyValue) Values() []interface{} {
	return []interface{}{
		s.Key,
		s.Value,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *KeyValue) Pointers() []interface{} {
	return []interface{}{
		&s.Key,
		&s.Value,
	}
}

// View returns View object for that struct.
func (s *KeyValue) View() reform.View {
	return KeyValueTable
}

// Table returns Table object for that record.
func (s *KeyValue) Table() reform.Table {
	return KeyValueTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *KeyValue) PKValue() interface{} {
	return s.Key
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *KeyValue) PKPointer() interface{} {
	return &s.Key
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *KeyValue) HasPK() bool {
	return s.Key != KeyValueTable.z[KeyValueTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *KeyValue) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.Key = string(i64)
	} else {
		s.Key = pk.(string)
	}
}

// check interfaces
var (
	_ reform.View   = KeyValueTable
	_ reform.Struct = (*KeyValue)(nil)
	_ reform.Table  = KeyValueTable
	_ reform.Record = (*KeyValue)(nil)
	_ fmt.Stringer  = (*KeyValue)(nil)
)

func init() {
	parse.AssertUpToDate(&KeyValueTable.s, new(KeyValue))
}
