// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type oktaSSODetailsViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *oktaSSODetailsViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("okta_sso_details").
func (v *oktaSSODetailsViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *oktaSSODetailsViewType) Columns() []string {
	return []string{
		"client_id",
		"client_secret",
		"issuer_url",
		"scope",
		"created_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *oktaSSODetailsViewType) NewStruct() reform.Struct {
	return new(OktaSSODetails)
}

// OktaSSODetailsView represents okta_sso_details view or table in SQL database.
var OktaSSODetailsView = &oktaSSODetailsViewType{
	s: parse.StructInfo{
		Type:    "OktaSSODetails",
		SQLName: "okta_sso_details",
		Fields: []parse.FieldInfo{
			{Name: "ClientID", Type: "string", Column: "client_id"},
			{Name: "ClientSecret", Type: "string", Column: "client_secret"},
			{Name: "IssuerURL", Type: "string", Column: "issuer_url"},
			{Name: "Scope", Type: "string", Column: "scope"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
		},
		PKFieldIndex: -1,
	},
	z: new(OktaSSODetails).Values(),
}

// String returns a string representation of this struct or record.
func (s OktaSSODetails) String() string {
	res := make([]string, 5)
	res[0] = "ClientID: " + reform.Inspect(s.ClientID, true)
	res[1] = "ClientSecret: " + reform.Inspect(s.ClientSecret, true)
	res[2] = "IssuerURL: " + reform.Inspect(s.IssuerURL, true)
	res[3] = "Scope: " + reform.Inspect(s.Scope, true)
	res[4] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *OktaSSODetails) Values() []interface{} {
	return []interface{}{
		s.ClientID,
		s.ClientSecret,
		s.IssuerURL,
		s.Scope,
		s.CreatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *OktaSSODetails) Pointers() []interface{} {
	return []interface{}{
		&s.ClientID,
		&s.ClientSecret,
		&s.IssuerURL,
		&s.Scope,
		&s.CreatedAt,
	}
}

// View returns View object for that struct.
func (s *OktaSSODetails) View() reform.View {
	return OktaSSODetailsView
}

// check interfaces
var (
	_ reform.View   = OktaSSODetailsView
	_ reform.Struct = (*OktaSSODetails)(nil)
	_ fmt.Stringer  = (*OktaSSODetails)(nil)
)

func init() {
	parse.AssertUpToDate(&OktaSSODetailsView.s, new(OktaSSODetails))
}
