// Code generated by go-swagger; DO NOT EDIT.

package postgre_sql

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/percona/pmm-managed/api/swagger/models"
)

// DiscoverMixin4Reader is a Reader for the DiscoverMixin4 structure.
type DiscoverMixin4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DiscoverMixin4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDiscoverMixin4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDiscoverMixin4OK creates a DiscoverMixin4OK with default headers values
func NewDiscoverMixin4OK() *DiscoverMixin4OK {
	return &DiscoverMixin4OK{}
}

/*DiscoverMixin4OK handles this case with default header values.

(empty)
*/
type DiscoverMixin4OK struct {
	Payload *models.APIPostgreSQLDiscoverResponse
}

func (o *DiscoverMixin4OK) Error() string {
	return fmt.Sprintf("[POST /v0/postgresql/discover][%d] discoverMixin4OK  %+v", 200, o.Payload)
}

func (o *DiscoverMixin4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPostgreSQLDiscoverResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
