// Code generated by go-swagger; DO NOT EDIT.

package postgre_sql

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/percona/pmm-managed/api/swagger/models"
)

// NewDiscoverMixin4Params creates a new DiscoverMixin4Params object
// with the default values initialized.
func NewDiscoverMixin4Params() *DiscoverMixin4Params {
	var ()
	return &DiscoverMixin4Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDiscoverMixin4ParamsWithTimeout creates a new DiscoverMixin4Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDiscoverMixin4ParamsWithTimeout(timeout time.Duration) *DiscoverMixin4Params {
	var ()
	return &DiscoverMixin4Params{

		timeout: timeout,
	}
}

// NewDiscoverMixin4ParamsWithContext creates a new DiscoverMixin4Params object
// with the default values initialized, and the ability to set a context for a request
func NewDiscoverMixin4ParamsWithContext(ctx context.Context) *DiscoverMixin4Params {
	var ()
	return &DiscoverMixin4Params{

		Context: ctx,
	}
}

// NewDiscoverMixin4ParamsWithHTTPClient creates a new DiscoverMixin4Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDiscoverMixin4ParamsWithHTTPClient(client *http.Client) *DiscoverMixin4Params {
	var ()
	return &DiscoverMixin4Params{
		HTTPClient: client,
	}
}

/*DiscoverMixin4Params contains all the parameters to send to the API endpoint
for the discover mixin4 operation typically these are written to a http.Request
*/
type DiscoverMixin4Params struct {

	/*Body*/
	Body *models.APIPostgreSQLDiscoverRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the discover mixin4 params
func (o *DiscoverMixin4Params) WithTimeout(timeout time.Duration) *DiscoverMixin4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the discover mixin4 params
func (o *DiscoverMixin4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the discover mixin4 params
func (o *DiscoverMixin4Params) WithContext(ctx context.Context) *DiscoverMixin4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the discover mixin4 params
func (o *DiscoverMixin4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the discover mixin4 params
func (o *DiscoverMixin4Params) WithHTTPClient(client *http.Client) *DiscoverMixin4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the discover mixin4 params
func (o *DiscoverMixin4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the discover mixin4 params
func (o *DiscoverMixin4Params) WithBody(body *models.APIPostgreSQLDiscoverRequest) *DiscoverMixin4Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the discover mixin4 params
func (o *DiscoverMixin4Params) SetBody(body *models.APIPostgreSQLDiscoverRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DiscoverMixin4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
